# Generated by Django 4.1.7 on 2023-03-17 06:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("documento", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=100, null=True, unique=True)),
                ("celular", models.CharField(max_length=20)),
                ("telefone", models.CharField(max_length=20, null=True)),
                ("pessoa_fisica", models.BooleanField(default=True)),
                ("funcionario", models.BooleanField(default=False)),
                ("fornecedor", models.BooleanField(default=False)),
                ("data_cadastro", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
