# Generated by Django 4.1.7 on 2023-03-17 06:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rua", models.CharField(max_length=70, null=True)),
                ("numero", models.CharField(max_length=15, null=True)),
                ("bairro", models.CharField(max_length=45, null=True)),
                ("cidade", models.CharField(max_length=45, null=True)),
                ("estado", models.CharField(max_length=20, null=True)),
                ("cep", models.CharField(max_length=20, null=True)),
                ("complemento", models.CharField(max_length=45, null=True)),
                (
                    "cliente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endereco",
                        to="clientes.cliente",
                    ),
                ),
            ],
        ),
    ]
