# Generated by Django 4.1.7 on 2023-03-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=70, null=True)),
                ("numero", models.CharField(max_length=15, null=True)),
                ("bairro", models.CharField(max_length=45, null=True)),
                ("cidade", models.CharField(max_length=45, null=True)),
                ("estado", models.CharField(max_length=20, null=True)),
                ("cep", models.CharField(max_length=20, null=True)),
                ("complemento", models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
